version: "3.1"
services:
    mysql:
      image: mysql:5.7
      container_name: go-mysql
      working_dir: /application
      command: mysqld --sql_mode=""
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=golang
        - MYSQL_USER=golang
        - MYSQL_PASSWORD=golang
      ports:
        - "3306:3306"

    webserver:
      build: docker/nginx
      container_name: go-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      links:
        - go
      ports:
       - "80:80"
       - "443:443"

    go:
      image: cosmtrek/air
      working_dir: /app
      container_name: go_app
      volumes:
        - ./:/app
      links:
        - mysql
      ports:
        - "8080:8080"